version: '3.4'

services:
  app:
    build: .
    restart: always
    environment:
      - MYSQL_HOST=db
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    expose:
      - '8080'
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    container_name: db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root_san
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
